name: build

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9"]

    steps:
      - id: checkout_repo
        name: checkout changes from repository
        uses: actions/checkout@v3

      - id: setup_python
        name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - id: prepare_environment
        name: set PYTHONPATH
        run: export PYTHONPATH="$PWD"

      - id: setup_poetry
        name: Install and configure Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.2.2
          virtualenvs-create: true
          virtualenvs-in-project: true
          virtualenvs-path: ~/virtualenvs
          installer-parallel: true
        
      - id: cache_poetry
        name: Cache project dependencies
        uses: actions/cache@v1
        with:
          path: ~/.virtualenvs
          key: poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            poetry-${{ hashFiles('**/poetry.lock') }}

      - id: code_quality
        name: Code Qaulity Check
        run: poetry run black . --check

      - id: run_tests
        name: Running all tests
        run: poetry run pytest



